version: '2'
services:
  coin-api:
    container_name: coin-api
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: 'on-failure'
    ports: 
      - 5000:5000
  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:6.7.2
    container_name: grafana
    volumes:
    #  - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports: 
      - 3000:3000
    #networks:
    #  - monitor-net
    labels:
      org.label-schema.group: "monitoring"      