apiVersion: v1
kind: Service
metadata:
  name: b2b-monitor
  namespace: aws-poc
  labels:
    app: b2b-monitor-svc
spec:
  ports:
  - name: metrics
    port: 80
    protocol: TCP
    targetPort: 8082
  selector:
    app: b2b-monitor  
  type: ClusterIP

