apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: rockman88v/b2b-monitor:latest
          ports:
            - containerPort: 8082
          env:
            - name: DOMAIN
              value: "https://poc-projectnet.staging.propertyguru.vn"
            - name: PORT
              value: "8082"

