{
 "title": "Flip-Coins",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Head statistics",
   "type": "graph",
   "description": "Head statistics",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "heads_count_total" }
   ]
  },
  {
   "title": "Tail statistics",
   "type": "graph",
   "description": "Tail statistics",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "tails_count_total" }
   ]
  },
  {
   "title": "Flip statistics",
   "type": "graph",
   "description": "Flip statistics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "flip_count_total" }
   ]
  }
 ]
}